"""add_ml_retry_count

Revision ID: 0421481d4869
Revises: 34c2958e2cdc
Create Date: 2026-07-10 08:41:15.835718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0421481d4869'
down_revision: Union[str, Sequence[str], None] = '34c2958e2cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('ml_retry_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'ml_retry_count')
    # ### end Alembic commands ###
