"""add_ml_status_and_detection_metadata

Revision ID: 34c2958e2cdc
Revises: 4a902b0658e2
Create Date: 2026-07-10 01:00:45.118258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c2958e2cdc'
down_revision: Union[str, Sequence[str], None] = '4a902b0658e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('ml_status', sa.Enum('pending', 'success', 'no_objects_found', 'failed', name='mlstatus'), nullable=False, server_default='pending'))
    op.add_column('reports', sa.Column('detection_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'detection_metadata')
    op.drop_column('reports', 'ml_status')
    # ### end Alembic commands ###
